openapi: 3.0.3
info:
  title: IoT Relay & Sensors API
  version: 1.0.0
  description: API untuk komunikasi dengan perangkat IoT (Relay & Sensors).
servers:
  - url: http://http://103.151.221.230:9098/api
    description: API Server

paths:
  /relay/update:
    post:
      summary: Update status relay
      description: Update status koneksi relay (8 channel sekaligus).
      tags:
        - Relay
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mac_address
                - relay_connection
                - relay_condition
              properties:
                mac_address:
                  type: string
                  example: "AA:BB:CC:DD:EE:FF"
                relay_connection:
                  type: integer
                  enum: [0, 1]
                  example: 1
                relay_condition:
                  type: array
                  items:
                    type: integer
                    enum: [0, 1]
                  minItems: 8
                  maxItems: 8
                  example: [1, 0, 1, 0, 0, 1, 1, 0]
      responses:
        '200':
          description: Update berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
        '422':
          description: Validasi gagal
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: failed
                  message:
                    type: string
                    example: "The relay_condition field must have 8 items."
        '500':
          description: Server error

  /relay/command:
    get:
      summary: Ambil command relay
      description: Mendapatkan perintah relay (8 channel).
      tags:
        - Relay
      parameters:
        - in: query
          name: mac_address
          required: true
          schema:
            type: string
          example: "AA:BB:CC:DD:EE:FF"
      responses:
        '200':
          description: Berhasil ambil perintah relay
          content:
            application/json:
              schema:
                type: object
                properties:
                  relay_command:
                    type: array
                    items:
                      type: integer
                      enum: [0, 1]
                    example: [0, 1, 0, 0, 1, 1, 0, 0]
        '422':
          description: Validasi gagal
        '500':
          description: Server error

  /sensors:
    post:
      summary: Simpan data sensor
      description: Kirim data sensor (Epever, RS485, Arduino) ke server.
      tags:
        - Sensors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mac_address
                - sensors
                - type
              properties:
                mac_address:
                  type: string
                  example: "AA:BB:CC:DD:EE:FF"
                type:
                  type: string
                  enum: [epever_data, sensor_rs485, sensor_arduino]
                  example: epever_data
                sensors:
                  type: object
                  additionalProperties: true
                  example:
                    voltage: 12.5
                    current: 3.2
                    temperature: 28
      responses:
        '201':
          description: Data berhasil disimpan
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Data Tersimpan"
        '422':
          description: Validasi gagal
        '500':
          description: Gagal menyimpan data sensor
